#Wine Quality Prediction Using Support Vector Machine

Get Understanding about Data

white wine data has twelve variables
    1.fixed acidity
    2.volatile acidity
    3.citric acid
    4.residual sugar
    5.chlorides
    6.free sulfur dioxide
    7.total sulfur dioxide
    8.density
    9.pH
    10.sulphates
    11.alcohol
    12.quality

Import Library

In [2]:
import pandas as pd

In [3]:
import numpy as np

Import CSV as DataFrame

Use URL of file directly

In [17]:
file_path = 'WhiteWineQuality.csv'
df = pd.read_csv(file_path, sep=';')

Get the first five rows of Dataframe

In [18]:
df.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.0              0.27         0.36            20.7      0.045   
1            6.3              0.30         0.34             1.6      0.049   
2            8.1              0.28         0.40             6.9      0.050   
3            7.2              0.23         0.32             8.5      0.058   
4            7.2              0.23         0.32             8.5      0.058   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 45.0                 170.0   1.0010  3.00       0.45   
1                 14.0                 132.0   0.9940  3.30       0.49   
2                 30.0                  97.0   0.9951  3.26       0.44   
3                 47.0                 186.0   0.9956  3.19       0.40   
4                 47.0                 186.0   0.9956  3.19       0.40   

   alcohol  quality  
0      8.8        6  
1      9.5        6  
2     10.1        6  
3      9.9        6  
4      9.9        6

Get Information about DataFrame

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4898 entries, 0 to 4897
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   fixed acidity         4898 non-null   float64
 1   volatile acidity      4898 non-null   float64
 2   citric acid           4898 non-null   float64
 3   residual sugar        4898 non-null   float64
 4   chlorides             4898 non-null   float64
 5   free sulfur dioxide   4898 non-null   float64
 6   total sulfur dioxide  4898 non-null   float64
 7   density               4898 non-null   float64
 8   pH                    4898 non-null   float64
 9   sulphates             4898 non-null   float64
 10  alcohol               4898 non-null   float64
 11  quality               4898 non-null   int64  
dtypes: float64(11), int64(1)
memory usage: 459.3 KB


Get the Summary Statistics

In [20]:
df.describe()

fixed acidity  volatile acidity  citric acid  residual sugar  \
count    4898.000000       4898.000000  4898.000000     4898.000000   
mean        6.854788          0.278241     0.334192        6.391415   
std         0.843868          0.100795     0.121020        5.072058   
min         3.800000          0.080000     0.000000        0.600000   
25%         6.300000          0.210000     0.270000        1.700000   
50%         6.800000          0.260000     0.320000        5.200000   
75%         7.300000          0.320000     0.390000        9.900000   
max        14.200000          1.100000     1.660000       65.800000   

         chlorides  free sulfur dioxide  total sulfur dioxide      density  \
count  4898.000000          4898.000000           4898.000000  4898.000000   
mean      0.045772            35.308085            138.360657     0.994027   
std       0.021848            17.007137             42.498065     0.002991   
min       0.009000             2.000000              9.000000     0.987110   
25%       0.036000            23.000000            108.000000     0.991723   
50%       0.043000            34.000000            134.000000     0.993740   
75%       0.050000            46.000000            167.000000     0.996100   
max       0.346000           289.000000            440.000000     1.038980   

                pH    sulphates      alcohol      quality  
count  4898.000000  4898.000000  4898.000000  4898.000000  
mean      3.188267     0.489847    10.514267     5.877909  
std       0.151001     0.114126     1.230621     0.885639  
min       2.720000     0.220000     8.000000     3.000000  
25%       3.090000     0.410000     9.500000     5.000000  
50%       3.180000     0.470000    10.400000     6.000000  
75%       3.280000     0.550000    11.400000     6.000000  
max       3.820000     1.080000    14.200000     9.000000

Get Column Names

In [21]:
df.columns

Index(['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar',
       'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density',
       'pH', 'sulphates', 'alcohol', 'quality'],
      dtype='object')

In [ ]:
Get shape of DataFrame

In [22]:
df.shape

(4898, 12)

Get Unique Values(Class or Label) in y Variable

In [23]:
df['quality'].value_counts()

quality
6    2198
5    1457
7     880
8     175
4     163
3      20
9       5
Name: count, dtype: int64

In [24]:
df.groupby('quality').mean()

fixed acidity  volatile acidity  citric acid  residual sugar  \
quality                                                                 
3             7.600000          0.333250     0.336000        6.392500   
4             7.129448          0.381227     0.304233        4.628221   
5             6.933974          0.302011     0.337653        7.334969   
6             6.837671          0.260564     0.338025        6.441606   
7             6.734716          0.262767     0.325625        5.186477   
8             6.657143          0.277400     0.326514        5.671429   
9             7.420000          0.298000     0.386000        4.120000   

         chlorides  free sulfur dioxide  total sulfur dioxide   density  \
quality                                                                   
3         0.054300            53.325000            170.600000  0.994884   
4         0.050098            23.358896            125.279141  0.994277   
5         0.051546            36.432052            150.904598  0.995263   
6         0.045217            35.650591            137.047316  0.993961   
7         0.038191            34.125568            125.114773  0.992452   
8         0.038314            36.720000            126.165714  0.992236   
9         0.027400            33.400000            116.000000  0.991460   

               pH  sulphates    alcohol  
quality                                  
3        3.187500   0.474500  10.345000  
4        3.182883   0.476135  10.152454  
5        3.168833   0.482203   9.808840  
6        3.188599   0.491106  10.575372  
7        3.213898   0.503102  11.367936  
8        3.218686   0.486229  11.636000  
9        3.308000   0.466000  12.180000

Define y(dependent or label or target varibale) and X(independent or features or attribute variable)

In [25]:
y=df['quality']

In [26]:
y.shape

(4898,)

In [27]:
y

0       6
1       6
2       6
3       6
4       6
       ..
4893    6
4894    5
4895    6
4896    7
4897    6
Name: quality, Length: 4898, dtype: int64

In [28]:
X = df[['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar', 'chlorides',
        'free sulfur dioxide', 'total sulfur dioxide', 'density', 'pH', 'sulphates', 'alcohol']]

or use.drop function to define X

In [29]:
X=df.drop(['quality'], axis=1)

In [30]:
X.shape

(4898, 11)

In [31]:
X

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.0              0.27         0.36            20.7      0.045   
1               6.3              0.30         0.34             1.6      0.049   
2               8.1              0.28         0.40             6.9      0.050   
3               7.2              0.23         0.32             8.5      0.058   
4               7.2              0.23         0.32             8.5      0.058   
...             ...               ...          ...             ...        ...   
4893            6.2              0.21         0.29             1.6      0.039   
4894            6.6              0.32         0.36             8.0      0.047   
4895            6.5              0.24         0.19             1.2      0.041   
4896            5.5              0.29         0.30             1.1      0.022   
4897            6.0              0.21         0.38             0.8      0.020   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    45.0                 170.0  1.00100  3.00       0.45   
1                    14.0                 132.0  0.99400  3.30       0.49   
2                    30.0                  97.0  0.99510  3.26       0.44   
3                    47.0                 186.0  0.99560  3.19       0.40   
4                    47.0                 186.0  0.99560  3.19       0.40   
...                   ...                   ...      ...   ...        ...   
4893                 24.0                  92.0  0.99114  3.27       0.50   
4894                 57.0                 168.0  0.99490  3.15       0.46   
4895                 30.0                 111.0  0.99254  2.99       0.46   
4896                 20.0                 110.0  0.98869  3.34       0.38   
4897                 22.0                  98.0  0.98941  3.26       0.32   

      alcohol  
0         8.8  
1         9.5  
2        10.1  
3         9.9  
4         9.9  
...       ...  
4893     11.2  
4894      9.6  
4895      9.4  
4896     12.8  
4897     11.8  

[4898 rows x 11 columns]

Get X variables Standarized

Standardization of datasets is a common requirement for many machine learning estimators implemented in scikit-learn;they might behave badly if the individual features do not more or less look like standard normally distrubuted data: Gaussian with zero mean and unit variance 
Next apporach is go for MinMax Scaler

In [33]:
from sklearn.preprocessing import StandardScaler

In [34]:
ss= StandardScaler()

In [35]:
X= ss.fit_transform(X)

In [36]:
X

array([[ 1.72096961e-01, -8.17699008e-02,  2.13280202e-01, ...,
        -1.24692128e+00, -3.49184257e-01, -1.39315246e+00],
       [-6.57501128e-01,  2.15895632e-01,  4.80011213e-02, ...,
         7.40028640e-01,  1.34184656e-03, -8.24275678e-01],
       [ 1.47575110e+00,  1.74519434e-02,  5.43838363e-01, ...,
         4.75101984e-01, -4.36815783e-01, -3.36667007e-01],
       ...,
       [-4.20473102e-01, -3.79435433e-01, -1.19159198e+00, ...,
        -1.31315295e+00, -2.61552731e-01, -9.05543789e-01],
       [-1.60561323e+00,  1.16673788e-01, -2.82557040e-01, ...,
         1.00495530e+00, -9.62604939e-01,  1.85757201e+00],
       [-1.01304317e+00, -6.77100966e-01,  3.78559282e-01, ...,
         4.75101984e-01, -1.48839409e+00,  1.04489089e+00]])

Get Train Test Split

In [37]:
from sklearn.model_selection import train_test_split

In [38]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3,stratify=y, random_state=2529)

In [39]:
X_train.shape, X_test.shape, y_train.shape , y_test.shape

((3428, 11), (1470, 11), (3428,), (1470,))

Get Model Train

In [40]:
from sklearn.svm import SVC

In [41]:
svc=SVC()

In [43]:
svc.fit(X_train,y_train)

SVC()

Get Model Prediction

In [45]:
y_pred= svc.predict(X_test)

In [46]:
y_pred.shape

(1470,)

In [47]:
y_pred

array([5, 7, 5, ..., 5, 5, 5], dtype=int64)

Get Model Evaluation

In [48]:
from sklearn.metrics import confusion_matrix,classification_report

In [49]:
print(confusion_matrix(y_test, y_pred))

[[  0   0   1   5   0   0   0]
 [  0   2  25  22   0   0   0]
 [  0   3 273 160   1   0   0]
 [  0   0 122 515  23   0   0]
 [  0   0   6 191  67   0   0]
 [  0   0   0  39  14   0   0]
 [  0   0   0   0   1   0   0]]


In [52]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           3       0.00      0.00      0.00         6
           4       0.40      0.04      0.07        49
           5       0.64      0.62      0.63       437
           6       0.55      0.78      0.65       660
           7       0.63      0.25      0.36       264
           8       0.00      0.00      0.00        53
           9       0.00      0.00      0.00         1

    accuracy                           0.58      1470
   macro avg       0.32      0.24      0.25      1470
weighted avg       0.57      0.58      0.55      1470



C:\Users\jaswa\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\jaswa\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\jaswa\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Get Model Re-turn with Two Class Created for Wine Quality

Wine Quality 3,4,5 labelled as 0

Wine Quality 6,7,8,9 labelled as 1

In [53]:
y=df['quality'].apply(lambda y_value:1 if y_value >= 6 else 0)

In [54]:
y.value_counts()

quality
1    3258
0    1640
Name: count, dtype: int64

Get Train Test Split

In [55]:
from sklearn.model_selection import train_test_split

In [56]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3,stratify=y, random_state=2529)

In [57]:
X_train.shape, X_test.shape, y_train.shape , y_test.shape

((3428, 11), (1470, 11), (3428,), (1470,))

Get Model Train

In [58]:
from sklearn.svm import SVC

In [59]:
svc=SVC()

In [60]:
svc.fit(X_train, y_train)

SVC()

Get Model Prediction

In [62]:
y_pred = svc.predict(X_test)

In [63]:
y_pred.shape

(1470,)

In [64]:
y_pred

array([0, 1, 1, ..., 1, 1, 1], dtype=int64)

Get Model Evaluation

In [65]:
from sklearn.metrics import confusion_matrix,classification_report

In [66]:
print(confusion_matrix(y_test, y_pred))

[[289 203]
 [124 854]]


In [67]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.70      0.59      0.64       492
           1       0.81      0.87      0.84       978

    accuracy                           0.78      1470
   macro avg       0.75      0.73      0.74      1470
weighted avg       0.77      0.78      0.77      1470



Get Model Re-run with Two Class Created for Wine Quality

Wine Quality 3,4,5 labelled as 0

Wine Quality 6,7,8,9 labelled as 1

In [68]:
y=df['quality'].apply(lambda y_value:1 if y_value >= 6 else 0)

In [69]:
y.value_counts()

quality
1    3258
0    1640
Name: count, dtype: int64

Get Train Test Split

In [71]:
from sklearn.model_selection import train_test_split

In [72]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3,stratify=y, random_state=2529)

In [73]:
X_train.shape, X_test.shape, y_train.shape , y_test.shape

((3428, 11), (1470, 11), (3428,), (1470,))

Get Model Train

In [74]:
from sklearn.svm import SVC

In [75]:
svc=SVC()

In [76]:
svc.fit(X_train, y_train)

SVC()

Get Model Prediction

In [ ]:
y_pred = svc.predit(X_test)

In [78]:
y_pred.shape

(1470,)

In [77]:
y_pred

array([0, 1, 1, ..., 1, 1, 1], dtype=int64)

Get Model Evaluation

In [79]:
from sklearn.metrics import confusion_matrix,classification_report

In [80]:
print(confusion_matrix(y_test,y_pred))

[[289 203]
 [124 854]]


In [82]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.70      0.59      0.64       492
           1       0.81      0.87      0.84       978

    accuracy                           0.78      1470
   macro avg       0.75      0.73      0.74      1470
weighted avg       0.77      0.78      0.77      1470



Get Future Predictions

Lets Select a random sample from existing dataset as new new value

steps to follow

    1.extraxt random row using sample function

    2.separate X and y
    
    3.standardize X 
    
    4.predicte

In [83]:
df_new = df.sample(1)

In [84]:
df_new

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
3823            6.7              0.26         0.49             8.1      0.052   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
3823                 48.0                 197.0  0.99558  3.19       0.48   

      alcohol  quality  
3823      9.5        5

In [85]:
df_new.shape

(1, 12)

In [86]:
X_new=df_new.drop(['quality'],axis=1)

In [87]:
X_new= ss.fit_transform(X_new)

In [88]:
y_pred_new= svc.predict(X_new)

In [89]:
y_pred_new

array([1], dtype=int64)